import React, { useState } from "react"
import Link from "next/link"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Page from './page'
import Navbar from './Navbar'

const Home: NextPage = (props) => {
  const [ open, setOpen ]: any = useState(false)
  return (
    // <div className={`container`}>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar open={open} setOpen={setOpen}/>
      <Page open={open} setOpen={setOpen}/>
    </div>
  )
}

export default Home
