import React from 'react'
// import App, { Container } from 'next/app'
import Link from "next/link"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Page from './page'
import Navbar from './Navbar'

const Home: NextPage = (props) => {
  return (
    // <div className={`container`}>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Page />
    </div>
  )
}

export default Home
