import React, { useState } from "react"
import Link from "next/link"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Page from '../Components/page'
import Navbar from '../Components/redux/Navbar'
import { Provider } from "react-redux";
import { createStore } from "redux";
import Reducer, { initialState } from "../Components/redux/Reducer";


const store = createStore(Reducer, initialState);
const Home: NextPage = (props) => {
  const [ open, setOpen ]: any = useState(false)
  return (
    <Provider store={store}>
    <div className="AllPageMainDiv">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
        <Navbar open={open} setOpen={setOpen}/>
        <Page open={open} setOpen={setOpen}/>
      </body>
    </div>
    </Provider>
  )
}

export default Home
